clear all;

figure;

flopscol = 5;
msize = 5;
fontsize = 16;
legend_loc = 'SouthEast';
max_perf = 24.8;
nth = 1;
y_begin = 0;
y_end = max_perf * 1.00;

data_peak( 1, 1:2 ) = [     0 max_perf ];
data_peak( 2, 1:2 ) = [  2000 max_perf ];

data_matrix = data_st_dgemm_asm_blis;

run tmkl
x_axis( :, 1 ) = data_matrix( :, 1 );
bli_1abc = line( x_axis( :, 1 ), ...
                 data_matrix( :, flopscol ) / nth, ...
                 'Color','k', ...
                 'LineStyle','-' );
hold on; ax1 = gca;


run output_st_dgemm_asm_blis_rs2_ab
bli_2ab  = line( x_axis( :, 1 ), ...
                 data_matrix( :, flopscol ) / nth, ...
                'Parent',ax1, ...
                'Color','r', ...
                'LineStyle','--' );

run output_st_dgemm_asm_blis_rs2_abc
bli_2abc = line( x_axis( :, 1 ), ...
                 data_matrix( :, flopscol ) / nth, ...
                'Parent',ax1, ...
                'Color','b', ...
                'LineStyle','--' );

run output_st_dgemm_asm_blis_rs2_abc_ws
bli_2abcw= line( x_axis( :, 1 ), ...
                 data_matrix( :, flopscol ) / nth, ...
                'Parent',ax1, ...
                'Color','b', ...
                'Marker','s', ...
                'LineStyle',':' );

run output_st_dgemm_asm_blis_rs2_c
bli_2c   = line( x_axis( :, 1 ), ...
                 data_matrix( :, flopscol ) / nth, ...
                'Parent',ax1, ...
                'Color','g', ...
                'LineStyle','--' );

run output_st_dgemm_asm_blis_rs2_c_ws
bli_2cw  = line( x_axis( :, 1 ), ...
                 data_matrix( :, flopscol ) / nth, ...
                'Parent',ax1, ...
                'Color','g', ...
                'Marker','s', ...
                'LineStyle',':' );


ylim( ax1, [y_begin y_end] );

leg = legend( ...
[ bli_1abc ...
  bli_2ab ...
  bli_2c ...
  bli_2cw ...
  bli_2abc ...
  bli_2abcw ...
], ...
'dgemm rs = 1: A,B,C', ...
'dgemm rs = 2: A,B', ...
'dgemm rs = 2: C', ...
'dgemm rs = 2: C via ws', ...
'dgemm rs = 2: A,B,C', ...
'dgemm rs = 2: A,B,C via ws', ...
'Location', legend_loc );

peak     = line( data_peak( :, 1 ), ...
                 data_peak( :, 2 ), ...
                 'Color','k', ...
                 'LineStyle',':' );

set( leg,'Box','off' );
set( leg,'Color','none' );
set( leg,'FontSize',fontsize );

set( ax1,'FontSize',fontsize );
box on;

titl = title( 'gemm, double-precision (1 thread)' );
xlab = xlabel( ax1,'problem size (m = n; k = kc)' );
ylab = ylabel( ax1,'GFLOPS/core' );


export_fig( 'fig_dgemm_m1p_kcc_n1p_snb_st_perf.pdf', '-pdf', '-m2', '-painters', '-transparent' );

hold off;

